# Site settings
title: "Shuo"
description: "WU Shuo Curriculum Vitae"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "WU Shuo"
resume_title:                   "Electronic Engineering"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "wushuo@proton.me"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       ""
resume_contact_address:         "Tat Chee Avenue, Kowloon, Hong Kong"

resume_header_contact_info:     ""
display_header_contact_info:    "false"

resume_header_intro: "<p>Shuo is a MSc student studying in City University of Hong Kong. Before that, he graduated from Beijing Forestry University. Shuo is interested in media processing and video codec.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        ""

# Decide which sections to use
# comment out to hide
resume_section_experience:      false
resume_section_education:       true
resume_section_projects:        false
resume_section_skills:          true
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    false
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  #resume_github_url:             "https://github.com/d3vzahvv"
  #resume_twitter_url:           "http://twitter.com/jglovier"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  #resume_facebook_url:          "insert Facebook URL here"
  #resume_linkedin_url:          "https://www.linkedin.com/in/joelglovier"
  #resume_instagram_url:          "https://www.instagram.com/d3vzahvv/"
  #resume_website_url:            "https://wushuo.me"
  #resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      false

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
